In [1]:
import numpy as np

In [3]:
# creating a 1-D numpy array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a , b)
print(type(a))
print(type(b))


[1 2 3 4 5] [5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
print(a + b)
print(a * b)
print(a - b)

[ 6  8 10 12 14]
[ 5 12 21 32 45]
[-4 -4 -4 -4 -4]


### to create a multidimension array -> np.array([ [],[],[] ])

In [5]:
n2 = np.array([[1,2], [2,3]])
print(n2)

[[1 2]
 [2 3]]


In [6]:
n3 = np.array([[1,2,3], [4,5,6]])
print(n3)

[[1 2 3]
 [4 5 6]]


In [10]:
print(n2.shape) # no of rows and columns
print(n2.ndim) #no. of dimensions
print(n2.dtype) # data type of elements

(2, 2)
2
int32


In [18]:
np.arange(1,100, 5) #same like range() but for 1D arrays

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [21]:
np.random.randint(1,10,size = (2 ,3)) # for multi-dimension array

array([[2, 7, 7],
       [4, 4, 9]])

In [23]:
import os
os.cpu_count()

12

In [26]:
x = np.array([[14,6,17],[4,7,17],[7,7,6]])
y = np.array([[4,1,18],[1,14,15],[6,14,11]])
print(x @ y) #matrix multiplication (or np.dot(x,y))

[[164 336 529]
 [125 340 364]
 [ 71 189 297]]


In [28]:
print(x.prod()) # product of all elements in the array

199840032


In [29]:
x.mean() #mean of all elements

9.444444444444445

In [32]:
x.mean(axis=0) # mean of each column

array([ 8.33333333,  6.66666667, 13.33333333])

In [35]:
x.mean(axis=1) #mean of each row

array([12.33333333,  9.33333333,  6.66666667])

In [36]:
print(x.sum())
print(x.std()) #standard deviation
print(x.var()) #variance

85
4.786813161897337
22.913580246913583


In [38]:
a = np.array([1,2,3,4,5,6,7,8, 9])
print(np.percentile(a , 50)) #median
print(np.percentile(a , 25)) #1st quartile
print(np.percentile(a , 75)) #3rd quartile

5.0
3.0
7.0


In [39]:
# reshaping the array
a = np.random.randint(11, 100, (4, 4))
print(a)
print('2X8')
print(a.reshape(2,8))

[[15 48 93 56]
 [77 16 31 71]
 [15 44 81 99]
 [24 98 48 75]]
2X8
[[15 48 93 56 77 16 31 71]
 [15 44 81 99 24 98 48 75]]
