In [1]:
import numpy as np

In [3]:
# creating a 1-D numpy array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a , b)
print(type(a))
print(type(b))


[1 2 3 4 5] [5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
print(a + b)
print(a * b)
print(a - b)

[ 6  8 10 12 14]
[ 5 12 21 32 45]
[-4 -4 -4 -4 -4]


### to create a multidimension array -> np.array([ [],[],[] ])

In [5]:
n2 = np.array([[1,2], [2,3]])
print(n2)

[[1 2]
 [2 3]]


In [6]:
n3 = np.array([[1,2,3], [4,5,6]])
print(n3)

[[1 2 3]
 [4 5 6]]


In [10]:
print(n2.shape) # no of rows and columns
print(n2.ndim) #no. of dimensions
print(n2.dtype) # data type of elements

(2, 2)
2
int32


In [18]:
np.arange(1,100, 5) #same like range() but for 1D arrays

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [21]:
np.random.randint(1,10,size = (2 ,3)) # for multi-dimension array

array([[2, 7, 7],
       [4, 4, 9]])

In [23]:
import os
os.cpu_count()

12

In [26]:
x = np.array([[14,6,17],[4,7,17],[7,7,6]])
y = np.array([[4,1,18],[1,14,15],[6,14,11]])
print(x @ y) #matrix multiplication (or np.dot(x,y))

[[164 336 529]
 [125 340 364]
 [ 71 189 297]]


In [28]:
print(x.prod()) # product of all elements in the array

199840032


In [29]:
x.mean() #mean of all elements

9.444444444444445

In [32]:
x.mean(axis=0) # mean of each column

array([ 8.33333333,  6.66666667, 13.33333333])

In [35]:
x.mean(axis=1) #mean of each row

array([12.33333333,  9.33333333,  6.66666667])

In [36]:
print(x.sum())
print(x.std()) #standard deviation
print(x.var()) #variance

85
4.786813161897337
22.913580246913583


In [38]:
a = np.array([1,2,3,4,5,6,7,8, 9])
print(np.percentile(a , 50)) #median
print(np.percentile(a , 25)) #1st quartile
print(np.percentile(a , 75)) #3rd quartile

5.0
3.0
7.0


In [39]:
# reshaping the array
a = np.random.randint(11, 100, (4, 4))
print(a)
print('2X8')
print(a.reshape(2,8))

[[15 48 93 56]
 [77 16 31 71]
 [15 44 81 99]
 [24 98 48 75]]
2X8
[[15 48 93 56 77 16 31 71]
 [15 44 81 99 24 98 48 75]]


# dictionary
- creating
- traversal
- methods
- sorting
- comprehension 

syntax:


{

    key:value,

    key:value,
    
    key:value,
    
}

In [113]:
fruits = {
    'apple': 'red',
    'banana': 'yellow',
    'cherry': 'red',
    'orange' : 'orange'
}
print(fruits)

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red', 'orange': 'orange'}


In [114]:
temp = {
    'lucknow': [25, 30, 35],
    'delhi': [30, 35, 40],
    'chennai': [24, 23, 22]
}
print(temp)

{'lucknow': [25, 30, 35], 'delhi': [30, 35, 40], 'chennai': [24, 23, 22]}


In [115]:
info = dict(name = 'raju', age=25, marks=[56, 73, 67])
print(info)

{'name': 'raju', 'age': 25, 'marks': [56, 73, 67]}


In [116]:
# nested dictionary
report =dict(
    alex = dict(english= 25, maths= 90, science= 78),
    rahul = dict(english= 56, maths= 76, science= 45)
)
print(report)

{'alex': {'english': 25, 'maths': 90, 'science': 78}, 'rahul': {'english': 56, 'maths': 76, 'science': 45}}


In [117]:
from pprint import pp #pretty print
pp(report)

{'alex': {'english': 25, 'maths': 90, 'science': 78},
 'rahul': {'english': 56, 'maths': 76, 'science': 45}}


In [118]:
fruits['cherry']

'red'

In [119]:
print(report['alex'])
print(report['alex']['maths'])

{'english': 25, 'maths': 90, 'science': 78}
90


In [120]:
print(temp['delhi'][0])
print(temp['delhi'][-1])
print('avg temp od delhi is', sum(temp['delhi'])/len(temp['delhi']))

30
40
avg temp od delhi is 35.0


In [121]:
# all keys of a dictionary
print(fruits.keys()) #not a list but a special object ,can be type casted into a list

dict_keys(['apple', 'banana', 'cherry', 'orange'])


In [122]:
fruit_names= list(fruits.keys())
print(fruit_names)

['apple', 'banana', 'cherry', 'orange']


In [123]:
# all values of dictionary
print(fruits.values())

dict_values(['red', 'yellow', 'red', 'orange'])


In [124]:
# traversal through keys
for item in fruits:
    print(item)

apple
banana
cherry
orange


In [125]:
for key in fruits:
    print(fruits[key])

red
yellow
red
orange


In [126]:
# traversal through .items() method
for k,v in fruits.items():
    print(k ,v)

apple red
banana yellow
cherry red
orange orange


In [127]:
# traverse only values
for i in fruits.values():
    print(i)

red
yellow
red
orange


In [128]:
# total marks of all students
for student ,marks in report.items():
    print(student)
    print(sum(marks.values()))

alex
193
rahul
177


In [129]:
# there is no method to add a single value to a dictionary (just a simple assignment)
fruits['mango'] = 'yellow' # adding a new value
pp(fruits)

{'apple': 'red',
 'banana': 'yellow',
 'cherry': 'red',
 'orange': 'orange',
 'mango': 'yellow'}


In [130]:
# adding small dictionary to a big dictionary
dry_fruits = {'date':'brown', 'almond': 'brown', 'cashew': 'white'}
fruits.update(dry_fruits) # merges dry_fruits to fruits dictionary
pp(fruits)

{'apple': 'red',
 'banana': 'yellow',
 'cherry': 'red',
 'orange': 'orange',
 'mango': 'yellow',
 'date': 'brown',
 'almond': 'brown',
 'cashew': 'white'}


In [131]:
# get method -> error free way to access data
#fruits['raisin'] #error: key not present
print(fruits.get('raisin')) #return none when key not present
print(fruits.get('date'))
print(fruits.get('guava', 'no value found')) #default value : specific value or message to be returned if key not present
print(fruits.get('guava', 404)) #default value : specific value or message to be returned if key not present

None
brown
no value found
404


In [132]:
# remove
fruits.pop('banana')  #remove by key => returns the value
pp(fruits)

{'apple': 'red',
 'cherry': 'red',
 'orange': 'orange',
 'mango': 'yellow',
 'date': 'brown',
 'almond': 'brown',
 'cashew': 'white'}


In [133]:
sorted?

Signature: sorted(iterable, /, *, key=None, reverse=False)
Docstring:
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
Type:      builtin_function_or_method

In [134]:
sorted(fruits) #sorts the keys

['almond', 'apple', 'cashew', 'cherry', 'date', 'mango', 'orange']

In [135]:
#sorting on keys
sorted(fruits.items())

[('almond', 'brown'),
 ('apple', 'red'),
 ('cashew', 'white'),
 ('cherry', 'red'),
 ('date', 'brown'),
 ('mango', 'yellow'),
 ('orange', 'orange')]

In [136]:
pp(sorted(fruits.items(), key= lambda i:i[1]))

[('date', 'brown'),
 ('almond', 'brown'),
 ('orange', 'orange'),
 ('apple', 'red'),
 ('cherry', 'red'),
 ('cashew', 'white'),
 ('mango', 'yellow')]


In [137]:
pp(sorted(fruits.items(), key= lambda i:i[1], reverse =True))

[('mango', 'yellow'),
 ('cashew', 'white'),
 ('apple', 'red'),
 ('cherry', 'red'),
 ('orange', 'orange'),
 ('date', 'brown'),
 ('almond', 'brown')]


In [138]:
#changing keys, value to upper case
clean_fruits= {}
for k,v in fruits.items():
    clean_fruits[k.lower()]= v.upper()
pp(clean_fruits)

{'apple': 'RED',
 'cherry': 'RED',
 'orange': 'ORANGE',
 'mango': 'YELLOW',
 'date': 'BROWN',
 'almond': 'BROWN',
 'cashew': 'WHITE'}


In [139]:
# the comprehension way
clean_fruits= {k.lower(): v.upper() for k,v in fruits.items()}
pp(clean_fruits)

{'apple': 'RED',
 'cherry': 'RED',
 'orange': 'ORANGE',
 'mango': 'YELLOW',
 'date': 'BROWN',
 'almond': 'BROWN',
 'cashew': 'WHITE'}


In [142]:
avg_temp = {city: sum(data)/len(data) for city, data in temp.items()}
pp(avg_temp)

{'lucknow': 30.0, 'delhi': 35.0, 'chennai': 23.0}
